test_that("failure", {
  fail("Failure!")
})
